# Release Pipelineå·¥å…·ç»Ÿä¸€å®‰è£…Action
# å‡å°‘Sentry CLIå’Œjqå·¥å…·åœ¨å¤šä¸ªjobä¸­çš„é‡å¤å®‰è£…

name: 'Setup Release Tools'
description: 'ç»Ÿä¸€å®‰è£…Releaseæµç¨‹éœ€è¦çš„å·¥å…·ï¼ˆSentry CLI, jqç­‰ï¼‰'

inputs:
  sentry-token:
    description: 'Sentryè®¤è¯token'
    required: false
  skip-sentry:
    description: 'è·³è¿‡Sentry CLIå®‰è£…'
    required: false
    default: 'false'

outputs:
  sentry-version:
    description: 'å·²å®‰è£…çš„Sentry CLIç‰ˆæœ¬'
    value: ${{ steps.sentry.outputs.version }}
  tools-ready:
    description: 'å·¥å…·å®‰è£…æ˜¯å¦å°±ç»ª'
    value: ${{ steps.validate.outputs.ready }}

runs:
  using: 'composite'
  steps:
    - name: ðŸ” æ£€æŸ¥å·¥å…·ç¼“å­˜
      id: cache
      shell: bash
      run: |
        # æ£€æŸ¥å·¥å…·æ˜¯å¦å·²å®‰è£…ä¸”ç‰ˆæœ¬åˆé€‚
        TOOLS_READY="false"

        if command -v jq >/dev/null 2>&1; then
          echo "âœ… jq already installed: $(jq --version)"
          TOOLS_READY="true"
        fi

        if [ "${{ inputs.skip-sentry }}" != "true" ] && npx --yes @sentry/cli --version >/dev/null 2>&1; then
          SENTRY_VER=$(npx --yes @sentry/cli --version 2>/dev/null | head -n1)
          echo "âœ… Sentry CLI already available: $SENTRY_VER"
          echo "version=$SENTRY_VER" >> $GITHUB_OUTPUT
        fi

        echo "ready=$TOOLS_READY" >> $GITHUB_OUTPUT

    - name: ðŸ› ï¸ å®‰è£…jqå·¥å…· (Windows)
      shell: pwsh
      if: steps.cache.outputs.ready != 'true'
      run: |
        if (-not (Get-Command jq -ErrorAction SilentlyContinue)) {
          Write-Host "ðŸ“¦ Installing jq tool..."
          if (Get-Command choco -ErrorAction SilentlyContinue) {
            choco install jq -y --no-progress
          } elseif (Get-Command winget -ErrorAction SilentlyContinue) {
            winget install stedolan.jq --accept-source-agreements --accept-package-agreements
          } else {
            Write-Host "âš ï¸ Neither chocolatey nor winget available, trying direct download..."
            Invoke-WebRequest -Uri "https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe" -OutFile "$env:TEMP\jq.exe"
            Move-Item "$env:TEMP\jq.exe" "$env:USERPROFILE\.local\bin\jq.exe" -Force
            echo "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          }
        } else {
          Write-Host "âœ… jq already installed"
        }

    - name: ðŸ”§ éªŒè¯Sentry CLI
      id: sentry
      shell: bash
      if: inputs.skip-sentry != 'true'
      run: |
        echo "ðŸ” éªŒè¯Sentry CLIå¯ç”¨æ€§..."
        if ! SENTRY_VER=$(npx --yes @sentry/cli --version 2>/dev/null | head -n1); then
          echo "âš ï¸ Sentry CLIä¸å¯ç”¨ï¼Œä½†ç»§ç»­æ‰§è¡Œ..."
          SENTRY_VER="unavailable"
        fi
        echo "version=$SENTRY_VER" >> $GITHUB_OUTPUT
        echo "âœ… Sentry CLIçŠ¶æ€: $SENTRY_VER"
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-token }}

    - name: âœ… å·¥å…·éªŒè¯å®Œæˆ
      id: validate
      shell: bash
      run: |
        echo "ðŸŽ¯ Releaseå·¥å…·å®‰è£…å®Œæˆ"
        echo "ready=true" >> $GITHUB_OUTPUT
