name: 'Hardened npm Install'
description: '统一的npm安装加固操作，解决系统性安装失败问题'
author: 'CI/CD Team'

inputs:
  working-directory:
    description: '工作目录'
    required: false
    default: '.'

outputs:
  npm-version:
    description: '安装的npm版本'
    value: ${{ steps.env-check.outputs.npm-version }}
  node-version:
    description: '安装的Node.js版本'
    value: ${{ steps.env-check.outputs.node-version }}

runs:
  using: 'composite'
  steps:
    - name: 🔧 npm安装加固版 (P1简化版)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔧 开始加固版npm安装..."

        # 简化版网络配置（基于2024最佳实践）
        npm config set fetch-retries 5
        npm config set fetch-retry-factor 2
        npm config set fetch-timeout 300000
        npm config set registry https://registry.npmjs.org/

        # 核心安装逻辑：3次重试 + 缓存清理
        for i in 1 2 3; do 
          echo "第 $i 次安装依赖尝试..."
          if npm ci --no-audit --no-fund; then
            echo "✅ 第 $i 次尝试成功"
            # 基本验证：node_modules存在
            if [ -d "node_modules" ]; then
              echo "✅ node_modules 目录验证通过"
              exit 0
            fi
          fi
          # 失败处理
          if [ $i -lt 3 ]; then
            echo "❌ 第 $i 次尝试失败，10秒后重试..."
            sleep 10
          else
            echo "🚨 所有重试失败，清理缓存后最后一次尝试..."
            npm cache clean --force
            npm ci --no-audit --no-fund
          fi
        done
        echo "✅ 依赖安装完成"

branding:
  icon: 'download'
  color: 'green'
