name: 'Windows-Focused npm Install'
description: 'Optimized npm installation for Windows-based CI/CD systems'
author: 'CI/CD Team'

inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version'
    required: false
    default: '20.x'

# Outputs removed to avoid referencing non-existent step IDs
# Use npm --version and node --version if version info is needed

runs:
  using: 'composite'
  steps:
    - name: Validate Node.js environment
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Validating Node.js environment setup..."

        # Verify Node.js is available and version
        if ! command -v node >/dev/null 2>&1; then
          echo "❌ ERROR: Node.js not found. Please ensure actions/setup-node@v4 runs before this action."
          exit 1
        fi

        node_version=$(node --version)
        echo "✅ Node.js version: $node_version"

        # Verify npm is available
        if ! command -v npm >/dev/null 2>&1; then
          echo "❌ ERROR: npm not found. Node.js installation may be incomplete."
          exit 1
        fi

        npm_version=$(npm --version)
        echo "✅ npm version: $npm_version"

    - name: Validate environment variables
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Validating critical environment variables..."
        echo "NODE_ENV: ${NODE_ENV:-not set}"
        echo "NPM_CONFIG_PRODUCTION: ${NPM_CONFIG_PRODUCTION:-not set}"

        # Validate devDependencies installation environment
        if [ "${NODE_ENV}" != "development" ] || [ "${NPM_CONFIG_PRODUCTION}" != "false" ]; then
          echo "WARNING: Environment variables may prevent devDependencies installation"
          echo "  Recommended: NODE_ENV=development, NPM_CONFIG_PRODUCTION=false"
        fi

    - name: Hardened npm install with ESM support
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Windows-focused npm installation with PowerShell compatibility
        set -euo pipefail

        echo "Starting Windows-focused npm installation..."
        echo "Platform: Windows, Runner: $RUNNER_OS"
        echo "Using project-level .npmrc config (network retries, caching, etc.)"

        # Show current npm config for debugging
        echo "Current npm configuration:"
        npm config list | grep -E "(fetch-retries|registry|fund|audit)" || true

        # Windows-focused ESM project handling: ensure devDependencies are correctly installed
        echo "Detected ESM project, installing dependencies for Windows environment..."

        # Set ESM-friendly npm environment variables
        export NPM_CONFIG_MAXSOCKETS="8"
        export NPM_CONFIG_FUND="false"
        export NPM_CONFIG_AUDIT="false"
        export NPM_CONFIG_PROGRESS="false"

        install_success=false

        # Windows-focused timeout function (simplified for Windows runners)
        run_with_timeout() {
          local timeout_seconds=$1
          shift
          
          # Windows runners always have timeout available
          timeout "${timeout_seconds}" "$@"
        }

        # Windows-optimized installation logic: 4 retries with progressive strategy
        for i in 1 2 3 4; do 
          echo "Attempt $i for Windows dependency installation (ESM project)..."
          
          if [ "$i" -eq 1 ]; then
            # First attempt: standard installation, 8-minute timeout
            if run_with_timeout 480 npm ci 2>&1 | tee npm_install.log; then
              install_success=true
            fi
          elif [ "$i" -eq 2 ]; then
            # Second attempt: increased timeout and network optimization
            echo "Increasing timeout for large dependency packages..."
            if run_with_timeout 720 npm ci --maxsockets=5 2>&1 | tee npm_install.log; then
              install_success=true
            fi
          elif [ "$i" -eq 3 ]; then
            # Third attempt: serial installation mode
            echo "Using serial installation mode (prevent network congestion)..."
            if run_with_timeout 900 npm ci --maxsockets=1 2>&1 | tee npm_install.log; then
              install_success=true
            fi
          else
            # Final attempt: extended timeout (npm ci, no lock changes)
            echo "Final attempt with extended timeout (npm ci, no lock changes)..."
            if run_with_timeout 900 npm ci 2>&1 | tee npm_install.log; then
              install_success=true
            fi
          fi
          
          if [ "$install_success" = "true" ]; then
            echo "SUCCESS: Attempt $i succeeded"
            
            # ESM project enhanced verification
            verification_errors=0
            
            # Windows-focused verification: Check critical devDependencies tools
            # Define tools as space-separated string for Windows compatibility
            dev_tools_list="eslint tsc vitest playwright tsx"
            
            for tool in $dev_tools_list; do
              # Enhanced check: node_modules/.bin first, then npm list verification
              if [ -f "node_modules/.bin/$tool" ] || [ -f "node_modules/.bin/${tool}.cmd" ]; then
                echo "SUCCESS: $tool (dev dependency) available in node_modules/.bin/"
              elif npm list "$tool" >/dev/null 2>&1; then
                echo "SUCCESS: $tool (dev dependency) found via npm list"
              else
                echo "WARNING: $tool not available in node_modules or npm registry"
                verification_errors=$((verification_errors + 1))
              fi
            done
            
            # Verify rollup native platform package for Windows
            echo "Verifying Rollup native platform package for Windows..."
            if node -e "require('@rollup/rollup-win32-x64-msvc'); console.log('rollup native ok')" 2>/dev/null; then
              echo "SUCCESS: @rollup/rollup-win32-x64-msvc platform package verified"
            else
              echo "WARNING: @rollup/rollup-win32-x64-msvc not found, using fallback"
              # Non-critical for Windows CI
            fi
            
            # Windows-focused node_modules structure verification
            if [ -d "node_modules" ] && [ -d "node_modules/.bin" ]; then
              # Simplified directory counting for Windows
              node_count=$(find node_modules -maxdepth 1 -type d 2>/dev/null | wc -l || echo "0")
              node_modules_size=$(du -sh node_modules 2>/dev/null | cut -f1 || echo "unknown")
              
              echo "SUCCESS: node_modules verification passed ($node_count packages, size: $node_modules_size)"
            else
              echo "ERROR: node_modules directory verification failed"
              verification_errors=$((verification_errors + 1))
            fi
            
            # Verify package.json type: module (Windows-focused)
            if grep -q '"type".*:.*"module"' package.json 2>/dev/null; then
              echo "SUCCESS: ESM module system verification passed"
            fi
            
            if [ "$verification_errors" -eq 0 ]; then
              echo "COMPLETE SUCCESS: Windows ESM project installation fully successful!"
            else
              echo "WARNING: Found $verification_errors verification issues, but installation succeeded"
            fi
            
            exit 0
          fi
          
          # Failure handling
          if [ "$i" -lt 4 ]; then
            wait_time=$((i * 15))
            echo "FAILED: Attempt $i failed, waiting ${wait_time} seconds before retry..."
            
            # Show error log snippet (Windows-focused)
            if [ -f npm_install.log ]; then
              echo "Error log snippet:"
              tail -10 npm_install.log 2>/dev/null || true
            fi
            
            sleep "$wait_time"
          fi
        done

        # All attempts failed
        echo "CRITICAL FAILURE: All 4 Windows ESM installation attempts failed!"
        if [ -f npm_install.log ]; then
          echo "Complete error log:"
          cat npm_install.log 2>/dev/null || echo "Could not read log file"
        fi
        exit 1

branding:
  icon: 'download'
  color: 'green'
