name: 'Run Tests'
description: 'Unified test runner for unit, E2E, security, coverage, smoke, and observability'

inputs:
  test-type:
    description: 'Test type'
    required: true
    type: choice
    default: 'unit'
    options:
      - unit
      - e2e
      - security
      - coverage
      - smoke
      - observability
  timeout:
    description: 'Timeout in milliseconds'
    required: false
    default: '300000'
  fail-fast:
    description: 'Fail fast on first error'
    required: false
    default: 'true'
  reporter:
    description: 'Reporter format'
    required: false
    default: 'default'
  output-file:
    description: 'Output file path for results'
    required: false

outputs:
  test-result:
    description: 'Test execution result'
    value: ${{ steps.test.outputs.result }}
  test-report:
    description: 'Test report path'
    value: ${{ steps.test.outputs.report_path }}

runs:
  using: 'composite'
  steps:
    - name: Run tests (Node wrapper)
      id: test
      shell: pwsh
      run: >-
        node scripts/ci/run-tests.mjs
        --test-type "${{ inputs.test-type }}"
        --timeout "${{ inputs.timeout }}"
        --fail-fast "${{ inputs.fail-fast }}"
        --reporter "${{ inputs.reporter }}"
        --output-file "${{ inputs.output-file }}"

    - name: Print summary
      shell: pwsh
      run: |
        if ('${{ steps.test.outputs.result }}' -eq 'success') {
          Write-Host '[tests] Status: PASS'
        } else {
          Write-Host '[tests] Status: FAIL'
        }
        if ('${{ steps.test.outputs.report_path }}' -ne '') {
          Write-Host "[tests] Report path: ${{ steps.test.outputs.report_path }}"
        }
