name: tasks-governance

# 最小权限原则
permissions:
  contents: read
  actions: read

# Infrastructure-level optimization: global environment variables
env:
  NODE_VERSION: '20.x'
  CI_RETRY_COUNT: '3'
  CI_TIMEOUT_MINUTES: '15'
  CACHE_STRATEGY: 'aggressive'

on:
  pull_request:
    paths:
      - 'docs/architecture/overlays/**'
      - 'scripts/overlay-map.json'
      - '.taskmaster/tasks/tasks.json'
      - 'scripts/**'
  push:
    branches: [main]

# ==================== 并发控制 ====================
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-tasks:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJson(env.CI_TIMEOUT_MINUTES) }}
    # P0修复：job级别环境变量确保devDependencies正确安装
    env:
      NODE_ENV: development
      NPM_CONFIG_PRODUCTION: 'false'

    # Infrastructure-level optimization: retry strategy
    strategy:
      fail-fast: false
      matrix:
        retry_attempt: [1]

    steps:
      - uses: actions/checkout@v4
        with:
          # Infrastructure optimization: shallow clone for faster checkout
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          # Infrastructure optimization: enhanced caching strategy
          cache-dependency-path: |
            package-lock.json
            package.json

      - name: 安装依赖 (使用强化npm-install action)
        uses: ./.github/actions/npm-install
        with:
          working-directory: '.'
          node-version: ${{ env.NODE_VERSION }}

      # 若 overlay-map 可自动生成，先重建并强制“已提交一致”
      - run: node scripts/build-overlay-map.mjs
      - name: ensure overlay-map committed
        run: |
          git diff --exit-code scripts/overlay-map.json || (echo "overlay-map.json changed; please commit." && exit 1)

      # 富化任务 & 结构/引用校验（Ajv + 自定义校验）
      - run: node scripts/enrich-tasks.mjs --tasks .taskmaster/tasks/tasks.json --map scripts/overlay-map.json
      - run: node scripts/validate-task-links.mjs --tasks .taskmaster/tasks/tasks.json
